name: mlsharp_flutter
description: "MLSharp 3D Maker - Flutter Reconstruction for Snapdragon GPU Acceleration"
publish_to: 'none'

version: 0.0.2-rc4+465

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  dio: ^5.3.0
  provider: ^6.0.0
  shared_preferences: ^2.2.0
  image_picker: ^1.0.0
  logger: ^2.0.0
  json_serializable: ^6.7.0
  model_viewer_plus: ^1.7.0
  flutter_gaussian_splatter: ^0.3.0
  package_info_plus: ^4.0.0
  path_provider: ^2.1.0
  intl: ^0.19.0
  file_picker: ^8.0.0  # 升级到最新版本以修复编译错误
  onnxruntime: ^1.4.1
  share_plus: ^12.0.1
  dynamic_color: ^1.0.2
  screenshot: ^3.0.0
  gal: ^2.3.1
  sentry_flutter: ^8.0.0
  connectivity_plus: ^5.0.2
  permission_handler: ^11.1.0
  uuid: ^4.0.0
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.2
  webview_flutter_wkwebview: ^3.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
